run-dist: #запуск исполняемого файла
	./build/install/app/bin/app

build: #сборка приложения
	./gradlew installDist

clean: #очистка
	./gradlew clean

lint: #запуск линтера checkStyle
	./gradlew checkstyleMain
